### ISSUE TITLE
install issue about ssl

### ISSUE THREAD

**Issue by liran319** [sockeye44/instavpn#65]
```Installing git,cron,python
Ok
Cloning git repo
Ok
12:59:38 INFO: Checking your OS version...
12:59:38 INFO: OK
12:59:38 INFO: Installing packages...
13:00:02 INFO: OK
13:00:02 INFO: Applying sysctl parameters...
13:00:02 INFO: OK
13:00:02 INFO: Creating random passwords...
13:00:02 INFO: OK
13:00:02 INFO: Other config files...
13:00:02 INFO: OK
13:00:02 INFO: Adding script to rc.local...
13:00:04 INFO: OK
13:00:04 INFO: Installing web UI...
13:00:05 CRITICAL: Failed installing web UI
Traceback (most recent call last):
  File "install.py", line 57, in <module>
    main()
  File "install.py", line 53, in main
    logger.critical("Failed installing web UI")
  File "/usr/lib/python2.7/logging/__init__.py", line 1197, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/root/workspace/instavpn/log.py", line 13, in emit
    url = pastee.PasteClient().paste(self.buff.getvalue())
  File "/root/workspace/instavpn/pastee.py", line 93, in paste
    self._conn.request("POST", "/submit", urllib.urlencode(params), headers)
  File "/usr/lib/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1220, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error```

**Comment by velsa** [comment]
Same here.
Any updates?

**Comment by savolkov** [comment]
+

**Comment by velsa** [comment]
I had to move to [OpenVPN](https://github.com/Angristan/OpenVPN-install) and it looks like I'm staying there.

**Comment by etomarat** [comment]
Same problem!

**Comment by sockeye44** [comment]
Sorry, this project is deprecated
