### ISSUE TITLE
CRITICAL: Failed installing web UI

### ISSUE THREAD

**Issue by cyberghost404** [sockeye44/instavpn#69]
CRITICAL: Failed installing web UI
Traceback (most recent call last):
  File "install.py", line 57, in <module>
    main()
  File "install.py", line 53, in main
    logger.critical("Failed installing web UI")
  File "/usr/lib/python2.7/logging/__init__.py", line 1197, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/root/instavpn/log.py", line 13, in emit
    url = pastee.PasteClient().paste(self.buff.getvalue())
  File "/root/instavpn/pastee.py", line 93, in paste
    self._conn.request("POST", "/submit", urllib.urlencode(params), headers)
  File "/usr/lib/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1220, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

OS: Ubuntu 14.04
Before that everything worked fine, now when you install here it gives, help please

**Comment by xeeoon** [comment]
same

**Comment by sockeye44** [comment]
Sorry, this project is deprecated
